# Generated by Django 5.1.1 on 2024-09-16 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_remove_product_categories_product_category'),
    ]

    operations = [
    ]
